# Generated by Django 4.0.5 on 2022-07-15 09:22

import child.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_child_agparscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='childregno',
            field=models.IntegerField(default=child.models.childregid),
        ),
    ]
