# Generated by Django 4.0.5 on 2022-07-15 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_child_childregno'),
    ]

    operations = [
        migrations.CreateModel(
            name='childtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_regno', models.IntegerField(default='')),
                ('heart_rate', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('muscle_tone', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('skin_colour', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('re_flex', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('Brea_thing', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('agpar_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
