# Generated by Django 4.0.5 on 2022-07-16 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_childtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='heartrate',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='childtest',
            name='heart_rate',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
    ]
