# Generated by Django 4.0.5 on 2022-07-18 19:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_alter_child_heartrate_alter_childtest_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Dob',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime.today)]),
        ),
    ]
