# Generated by Django 4.0.5 on 2022-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_blood_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_condtion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_nid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
