# Generated by Django 4.0.5 on 2022-06-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patient_blood_type_patient_patient_condtion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_blood_type',
            field=models.CharField(choices=[('A', ' A '), ('B', 'B'), ('C', 'C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_nid',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
