# Generated by Django 4.0.5 on 2022-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_alter_patient_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_roceord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bptop', models.IntegerField(default='', max_length=5)),
                ('bpbottom', models.CharField(default='', max_length=5)),
                ('hbc', models.IntegerField(default='')),
                ('usedrugs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('hiv', models.CharField(choices=[('Nagative', 'Nagative '), ('Positive', 'Posetive')], max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
                ('height', models.CharField(default='', max_length=100)),
                ('bmi', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('patientid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
