# Generated by Django 4.0.5 on 2022-06-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_rename_medical_roceord_medical_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
