# Generated by Django 4.0.5 on 2022-06-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_medical_record_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='bptop',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='weight',
            field=models.IntegerField(default=''),
        ),
    ]
