# Generated by Django 4.0.5 on 2022-06-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_medical_record_bptop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_assignednurse',
            field=models.IntegerField(default=0),
        ),
    ]
