# Generated by Django 4.0.5 on 2022-06-25 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0008_patient_patient_assignednurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_assignednurse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
