# Generated by Django 4.0.5 on 2022-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_patient_assignednurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
