# Generated by Django 4.0.5 on 2022-06-25 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_medical_record_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='bpbottom',
            field=models.CharField(default='', max_length=5, validators=[django.core.validators.MaxValueValidator(120)]),
        ),
    ]
