# Generated by Django 4.0.5 on 2022-06-29 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_medical_record_bpbottom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='bpbottom',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='bptop',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(160), django.core.validators.MinValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='hbc',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='hiv',
            field=models.CharField(choices=[('Negative', 'Negative '), ('Positive', 'Posetive')], max_length=100),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
