# Generated by Django 4.0.5 on 2022-07-18 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_patient_patient_assignednurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_date_added',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
